# Generated by Django 5.1 on 2025-05-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
